// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: role.proto

package role

import (
	"context"

	"go-zero-user/role-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AssignRoleReq    = pb.AssignRoleReq
	AssignRoleResp   = pb.AssignRoleResp
	CreateRoleReq    = pb.CreateRoleReq
	CreateRoleResp   = pb.CreateRoleResp
	DeleteRoleReq    = pb.DeleteRoleReq
	DeleteRoleResp   = pb.DeleteRoleResp
	GetRoleReq       = pb.GetRoleReq
	GetRoleResp      = pb.GetRoleResp
	GetUserRolesReq  = pb.GetUserRolesReq
	GetUserRolesResp = pb.GetUserRolesResp
	ListRoleReq      = pb.ListRoleReq
	ListRoleResp     = pb.ListRoleResp
	RoleInfo         = pb.RoleInfo
	UpdateRoleReq    = pb.UpdateRoleReq
	UpdateRoleResp   = pb.UpdateRoleResp

	Role interface {
		// 创建角色
		CreateRole(ctx context.Context, in *CreateRoleReq, opts ...grpc.CallOption) (*CreateRoleResp, error)
		// 获取角色
		GetRole(ctx context.Context, in *GetRoleReq, opts ...grpc.CallOption) (*GetRoleResp, error)
		// 更新角色
		UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*UpdateRoleResp, error)
		// 删除角色
		DeleteRole(ctx context.Context, in *DeleteRoleReq, opts ...grpc.CallOption) (*DeleteRoleResp, error)
		// 角色列表
		ListRole(ctx context.Context, in *ListRoleReq, opts ...grpc.CallOption) (*ListRoleResp, error)
		// 分配角色
		AssignRole(ctx context.Context, in *AssignRoleReq, opts ...grpc.CallOption) (*AssignRoleResp, error)
		// 获取用户角色
		GetUserRoles(ctx context.Context, in *GetUserRolesReq, opts ...grpc.CallOption) (*GetUserRolesResp, error)
	}

	defaultRole struct {
		cli zrpc.Client
	}
)

func NewRole(cli zrpc.Client) Role {
	return &defaultRole{
		cli: cli,
	}
}

// 创建角色
func (m *defaultRole) CreateRole(ctx context.Context, in *CreateRoleReq, opts ...grpc.CallOption) (*CreateRoleResp, error) {
	client := pb.NewRoleClient(m.cli.Conn())
	return client.CreateRole(ctx, in, opts...)
}

// 获取角色
func (m *defaultRole) GetRole(ctx context.Context, in *GetRoleReq, opts ...grpc.CallOption) (*GetRoleResp, error) {
	client := pb.NewRoleClient(m.cli.Conn())
	return client.GetRole(ctx, in, opts...)
}

// 更新角色
func (m *defaultRole) UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*UpdateRoleResp, error) {
	client := pb.NewRoleClient(m.cli.Conn())
	return client.UpdateRole(ctx, in, opts...)
}

// 删除角色
func (m *defaultRole) DeleteRole(ctx context.Context, in *DeleteRoleReq, opts ...grpc.CallOption) (*DeleteRoleResp, error) {
	client := pb.NewRoleClient(m.cli.Conn())
	return client.DeleteRole(ctx, in, opts...)
}

// 角色列表
func (m *defaultRole) ListRole(ctx context.Context, in *ListRoleReq, opts ...grpc.CallOption) (*ListRoleResp, error) {
	client := pb.NewRoleClient(m.cli.Conn())
	return client.ListRole(ctx, in, opts...)
}

// 分配角色
func (m *defaultRole) AssignRole(ctx context.Context, in *AssignRoleReq, opts ...grpc.CallOption) (*AssignRoleResp, error) {
	client := pb.NewRoleClient(m.cli.Conn())
	return client.AssignRole(ctx, in, opts...)
}

// 获取用户角色
func (m *defaultRole) GetUserRoles(ctx context.Context, in *GetUserRolesReq, opts ...grpc.CallOption) (*GetUserRolesResp, error) {
	client := pb.NewRoleClient(m.cli.Conn())
	return client.GetUserRoles(ctx, in, opts...)
}
