// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: role.proto

package server

import (
	"context"

	"github.com/haoyiwen/go-examples/go-zero/role-rpc/internal/logic"
	"github.com/haoyiwen/go-examples/go-zero/role-rpc/internal/svc"
	"github.com/haoyiwen/go-examples/go-zero/role-rpc/pb"
)

type RoleServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRoleServer
}

func NewRoleServer(svcCtx *svc.ServiceContext) *RoleServer {
	return &RoleServer{
		svcCtx: svcCtx,
	}
}

// 创建角色
func (s *RoleServer) CreateRole(ctx context.Context, in *pb.CreateRoleReq) (*pb.CreateRoleResp, error) {
	l := logic.NewCreateRoleLogic(ctx, s.svcCtx)
	return l.CreateRole(in)
}

// 获取角色
func (s *RoleServer) GetRole(ctx context.Context, in *pb.GetRoleReq) (*pb.GetRoleResp, error) {
	l := logic.NewGetRoleLogic(ctx, s.svcCtx)
	return l.GetRole(in)
}

// 更新角色
func (s *RoleServer) UpdateRole(ctx context.Context, in *pb.UpdateRoleReq) (*pb.UpdateRoleResp, error) {
	l := logic.NewUpdateRoleLogic(ctx, s.svcCtx)
	return l.UpdateRole(in)
}

// 删除角色
func (s *RoleServer) DeleteRole(ctx context.Context, in *pb.DeleteRoleReq) (*pb.DeleteRoleResp, error) {
	l := logic.NewDeleteRoleLogic(ctx, s.svcCtx)
	return l.DeleteRole(in)
}

// 角色列表
func (s *RoleServer) ListRole(ctx context.Context, in *pb.ListRoleReq) (*pb.ListRoleResp, error) {
	l := logic.NewListRoleLogic(ctx, s.svcCtx)
	return l.ListRole(in)
}

// 分配角色
func (s *RoleServer) AssignRole(ctx context.Context, in *pb.AssignRoleReq) (*pb.AssignRoleResp, error) {
	l := logic.NewAssignRoleLogic(ctx, s.svcCtx)
	return l.AssignRole(in)
}

// 获取用户角色
func (s *RoleServer) GetUserRoles(ctx context.Context, in *pb.GetUserRolesReq) (*pb.GetUserRolesResp, error) {
	l := logic.NewGetUserRolesLogic(ctx, s.svcCtx)
	return l.GetUserRoles(in)
}
