// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: proto/role.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 角色信息
type RoleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        int64                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleInfo) Reset() {
	*x = RoleInfo{}
	mi := &file_proto_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfo) ProtoMessage() {}

func (x *RoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfo.ProtoReflect.Descriptor instead.
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return file_proto_role_proto_rawDescGZIP(), []int{0}
}

func (x *RoleInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RoleInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RoleInfo) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RoleInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// 创建角色请求
type CreateRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleReq) Reset() {
	*x = CreateRoleReq{}
	mi := &file_proto_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleReq) ProtoMessage() {}

func (x *CreateRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleReq.ProtoReflect.Descriptor instead.
func (*CreateRoleReq) Descriptor() ([]byte, []int) {
	return file_proto_role_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoleReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateRoleReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// 创建角色响应
type CreateRoleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleResp) Reset() {
	*x = CreateRoleResp{}
	mi := &file_proto_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleResp) ProtoMessage() {}

func (x *CreateRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleResp.ProtoReflect.Descriptor instead.
func (*CreateRoleResp) Descriptor() ([]byte, []int) {
	return file_proto_role_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRoleResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 获取角色请求
type GetRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleReq) Reset() {
	*x = GetRoleReq{}
	mi := &file_proto_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleReq) ProtoMessage() {}

func (x *GetRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleReq.ProtoReflect.Descriptor instead.
func (*GetRoleReq) Descriptor() ([]byte, []int) {
	return file_proto_role_proto_rawDescGZIP(), []int{3}
}

func (x *GetRoleReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 获取角色响应
type GetRoleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *RoleInfo              `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleResp) Reset() {
	*x = GetRoleResp{}
	mi := &file_proto_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleResp) ProtoMessage() {}

func (x *GetRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleResp.ProtoReflect.Descriptor instead.
func (*GetRoleResp) Descriptor() ([]byte, []int) {
	return file_proto_role_proto_rawDescGZIP(), []int{4}
}

func (x *GetRoleResp) GetRole() *RoleInfo {
	if x != nil {
		return x.Role
	}
	return nil
}

// 更新角色请求
type UpdateRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        int64                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleReq) Reset() {
	*x = UpdateRoleReq{}
	mi := &file_proto_role_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleReq) ProtoMessage() {}

func (x *UpdateRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleReq.ProtoReflect.Descriptor instead.
func (*UpdateRoleReq) Descriptor() ([]byte, []int) {
	return file_proto_role_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRoleReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRoleReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRoleReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateRoleReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 更新角色响应
type UpdateRoleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleResp) Reset() {
	*x = UpdateRoleResp{}
	mi := &file_proto_role_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleResp) ProtoMessage() {}

func (x *UpdateRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleResp.ProtoReflect.Descriptor instead.
func (*UpdateRoleResp) Descriptor() ([]byte, []int) {
	return file_proto_role_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRoleResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 删除角色请求
type DeleteRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleReq) Reset() {
	*x = DeleteRoleReq{}
	mi := &file_proto_role_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleReq) ProtoMessage() {}

func (x *DeleteRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleReq.ProtoReflect.Descriptor instead.
func (*DeleteRoleReq) Descriptor() ([]byte, []int) {
	return file_proto_role_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRoleReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 删除角色响应
type DeleteRoleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleResp) Reset() {
	*x = DeleteRoleResp{}
	mi := &file_proto_role_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleResp) ProtoMessage() {}

func (x *DeleteRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleResp.ProtoReflect.Descriptor instead.
func (*DeleteRoleResp) Descriptor() ([]byte, []int) {
	return file_proto_role_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRoleResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 角色列表请求
type ListRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleReq) Reset() {
	*x = ListRoleReq{}
	mi := &file_proto_role_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleReq) ProtoMessage() {}

func (x *ListRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleReq.ProtoReflect.Descriptor instead.
func (*ListRoleReq) Descriptor() ([]byte, []int) {
	return file_proto_role_proto_rawDescGZIP(), []int{9}
}

func (x *ListRoleReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRoleReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 角色列表响应
type ListRoleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*RoleInfo            `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleResp) Reset() {
	*x = ListRoleResp{}
	mi := &file_proto_role_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleResp) ProtoMessage() {}

func (x *ListRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleResp.ProtoReflect.Descriptor instead.
func (*ListRoleResp) Descriptor() ([]byte, []int) {
	return file_proto_role_proto_rawDescGZIP(), []int{10}
}

func (x *ListRoleResp) GetRoles() []*RoleInfo {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ListRoleResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 分配角色请求
type AssignRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleIds       []int64                `protobuf:"varint,2,rep,packed,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleReq) Reset() {
	*x = AssignRoleReq{}
	mi := &file_proto_role_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleReq) ProtoMessage() {}

func (x *AssignRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleReq.ProtoReflect.Descriptor instead.
func (*AssignRoleReq) Descriptor() ([]byte, []int) {
	return file_proto_role_proto_rawDescGZIP(), []int{11}
}

func (x *AssignRoleReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AssignRoleReq) GetRoleIds() []int64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

// 分配角色响应
type AssignRoleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleResp) Reset() {
	*x = AssignRoleResp{}
	mi := &file_proto_role_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleResp) ProtoMessage() {}

func (x *AssignRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleResp.ProtoReflect.Descriptor instead.
func (*AssignRoleResp) Descriptor() ([]byte, []int) {
	return file_proto_role_proto_rawDescGZIP(), []int{12}
}

func (x *AssignRoleResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 获取用户角色请求
type GetUserRolesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRolesReq) Reset() {
	*x = GetUserRolesReq{}
	mi := &file_proto_role_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRolesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRolesReq) ProtoMessage() {}

func (x *GetUserRolesReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRolesReq.ProtoReflect.Descriptor instead.
func (*GetUserRolesReq) Descriptor() ([]byte, []int) {
	return file_proto_role_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserRolesReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 获取用户角色响应
type GetUserRolesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*RoleInfo            `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRolesResp) Reset() {
	*x = GetUserRolesResp{}
	mi := &file_proto_role_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRolesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRolesResp) ProtoMessage() {}

func (x *GetUserRolesResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRolesResp.ProtoReflect.Descriptor instead.
func (*GetUserRolesResp) Descriptor() ([]byte, []int) {
	return file_proto_role_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserRolesResp) GetRoles() []*RoleInfo {
	if x != nil {
		return x.Roles
	}
	return nil
}

var File_proto_role_proto protoreflect.FileDescriptor

const file_proto_role_proto_rawDesc = "" +
	"\n" +
	"\x10proto/role.proto\x12\x04role\"\x9b\x01\n" +
	"\bRoleInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x03R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"Y\n" +
	"\rCreateRoleReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\" \n" +
	"\x0eCreateRoleResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1c\n" +
	"\n" +
	"GetRoleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"1\n" +
	"\vGetRoleResp\x12\"\n" +
	"\x04role\x18\x01 \x01(\v2\x0e.role.RoleInfoR\x04role\"m\n" +
	"\rUpdateRoleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x03R\x06status\"*\n" +
	"\x0eUpdateRoleResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x1f\n" +
	"\rDeleteRoleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"*\n" +
	"\x0eDeleteRoleResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\">\n" +
	"\vListRoleReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\"J\n" +
	"\fListRoleResp\x12$\n" +
	"\x05roles\x18\x01 \x03(\v2\x0e.role.RoleInfoR\x05roles\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"C\n" +
	"\rAssignRoleReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\brole_ids\x18\x02 \x03(\x03R\aroleIds\"*\n" +
	"\x0eAssignRoleResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"*\n" +
	"\x0fGetUserRolesReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"8\n" +
	"\x10GetUserRolesResp\x12$\n" +
	"\x05roles\x18\x01 \x03(\v2\x0e.role.RoleInfoR\x05roles2\x8c\x03\n" +
	"\x04Role\x127\n" +
	"\n" +
	"CreateRole\x12\x13.role.CreateRoleReq\x1a\x14.role.CreateRoleResp\x12.\n" +
	"\aGetRole\x12\x10.role.GetRoleReq\x1a\x11.role.GetRoleResp\x127\n" +
	"\n" +
	"UpdateRole\x12\x13.role.UpdateRoleReq\x1a\x14.role.UpdateRoleResp\x127\n" +
	"\n" +
	"DeleteRole\x12\x13.role.DeleteRoleReq\x1a\x14.role.DeleteRoleResp\x121\n" +
	"\bListRole\x12\x11.role.ListRoleReq\x1a\x12.role.ListRoleResp\x127\n" +
	"\n" +
	"AssignRole\x12\x13.role.AssignRoleReq\x1a\x14.role.AssignRoleResp\x12=\n" +
	"\fGetUserRoles\x12\x15.role.GetUserRolesReq\x1a\x16.role.GetUserRolesRespB9Z7github.com/Hao-yiwen/go-examples/go-zero/role-rpc/pb;pbb\x06proto3"

var (
	file_proto_role_proto_rawDescOnce sync.Once
	file_proto_role_proto_rawDescData []byte
)

func file_proto_role_proto_rawDescGZIP() []byte {
	file_proto_role_proto_rawDescOnce.Do(func() {
		file_proto_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_role_proto_rawDesc), len(file_proto_role_proto_rawDesc)))
	})
	return file_proto_role_proto_rawDescData
}

var file_proto_role_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_role_proto_goTypes = []any{
	(*RoleInfo)(nil),         // 0: role.RoleInfo
	(*CreateRoleReq)(nil),    // 1: role.CreateRoleReq
	(*CreateRoleResp)(nil),   // 2: role.CreateRoleResp
	(*GetRoleReq)(nil),       // 3: role.GetRoleReq
	(*GetRoleResp)(nil),      // 4: role.GetRoleResp
	(*UpdateRoleReq)(nil),    // 5: role.UpdateRoleReq
	(*UpdateRoleResp)(nil),   // 6: role.UpdateRoleResp
	(*DeleteRoleReq)(nil),    // 7: role.DeleteRoleReq
	(*DeleteRoleResp)(nil),   // 8: role.DeleteRoleResp
	(*ListRoleReq)(nil),      // 9: role.ListRoleReq
	(*ListRoleResp)(nil),     // 10: role.ListRoleResp
	(*AssignRoleReq)(nil),    // 11: role.AssignRoleReq
	(*AssignRoleResp)(nil),   // 12: role.AssignRoleResp
	(*GetUserRolesReq)(nil),  // 13: role.GetUserRolesReq
	(*GetUserRolesResp)(nil), // 14: role.GetUserRolesResp
}
var file_proto_role_proto_depIdxs = []int32{
	0,  // 0: role.GetRoleResp.role:type_name -> role.RoleInfo
	0,  // 1: role.ListRoleResp.roles:type_name -> role.RoleInfo
	0,  // 2: role.GetUserRolesResp.roles:type_name -> role.RoleInfo
	1,  // 3: role.Role.CreateRole:input_type -> role.CreateRoleReq
	3,  // 4: role.Role.GetRole:input_type -> role.GetRoleReq
	5,  // 5: role.Role.UpdateRole:input_type -> role.UpdateRoleReq
	7,  // 6: role.Role.DeleteRole:input_type -> role.DeleteRoleReq
	9,  // 7: role.Role.ListRole:input_type -> role.ListRoleReq
	11, // 8: role.Role.AssignRole:input_type -> role.AssignRoleReq
	13, // 9: role.Role.GetUserRoles:input_type -> role.GetUserRolesReq
	2,  // 10: role.Role.CreateRole:output_type -> role.CreateRoleResp
	4,  // 11: role.Role.GetRole:output_type -> role.GetRoleResp
	6,  // 12: role.Role.UpdateRole:output_type -> role.UpdateRoleResp
	8,  // 13: role.Role.DeleteRole:output_type -> role.DeleteRoleResp
	10, // 14: role.Role.ListRole:output_type -> role.ListRoleResp
	12, // 15: role.Role.AssignRole:output_type -> role.AssignRoleResp
	14, // 16: role.Role.GetUserRoles:output_type -> role.GetUserRolesResp
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_role_proto_init() }
func file_proto_role_proto_init() {
	if File_proto_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_role_proto_rawDesc), len(file_proto_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_role_proto_goTypes,
		DependencyIndexes: file_proto_role_proto_depIdxs,
		MessageInfos:      file_proto_role_proto_msgTypes,
	}.Build()
	File_proto_role_proto = out.File
	file_proto_role_proto_goTypes = nil
	file_proto_role_proto_depIdxs = nil
}
