// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AssignRoleReq struct {
	UserId  int64   `json:"userId"`
	RoleIds []int64 `json:"roleIds"`
}

type AssignRoleResp struct {
	Success bool `json:"success"`
}

type CreateRoleReq struct {
	Name        string `json:"name"`
	Code        string `json:"code"`
	Description string `json:"description,optional"`
}

type CreateRoleResp struct {
	Id int64 `json:"id"`
}

type DeleteUserReq struct {
	Id int64 `path:"id"`
}

type DeleteUserResp struct {
	Success bool `json:"success"`
}

type GetUserInfoResp struct {
	User UserInfo `json:"user"`
}

type GetUserRolesResp struct {
	Roles []RoleInfo `json:"roles"`
}

type ListRoleReq struct {
	Page     int64 `form:"page,default=1"`
	PageSize int64 `form:"pageSize,default=10"`
}

type ListRoleResp struct {
	Roles []RoleInfo `json:"roles"`
	Total int64      `json:"total"`
}

type ListUserReq struct {
	Page     int64 `form:"page,default=1"`
	PageSize int64 `form:"pageSize,default=10"`
}

type ListUserResp struct {
	Users []UserInfo `json:"users"`
	Total int64      `json:"total"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Id           int64  `json:"id"`
	Username     string `json:"username"`
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpiresAt    int64  `json:"expiresAt"`
}

type LogoutResp struct {
	Success bool `json:"success"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refreshToken"`
}

type RefreshTokenResp struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpiresAt    int64  `json:"expiresAt"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email,optional"`
	Phone    string `json:"phone,optional"`
}

type RegisterResp struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
}

type RoleInfo struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Code        string `json:"code"`
	Description string `json:"description"`
	Status      int64  `json:"status"`
	CreatedAt   int64  `json:"createdAt"`
}

type UpdateRoleReq struct {
	Id          int64  `path:"id"`
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	Status      int64  `json:"status,optional"`
}

type UpdateRoleResp struct {
	Success bool `json:"success"`
}

type UpdateUserReq struct {
	Email  string `json:"email,optional"`
	Phone  string `json:"phone,optional"`
	Avatar string `json:"avatar,optional"`
}

type UpdateUserResp struct {
	Success bool `json:"success"`
}

type UserInfo struct {
	Id        int64  `json:"id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	Avatar    string `json:"avatar"`
	Status    int64  `json:"status"`
	CreatedAt int64  `json:"createdAt"`
}
