// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: auth.proto

package auth

import (
	"context"

	"github.com/haoyiwen/go-examples/go-zero/auth-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GenerateTokenReq  = pb.GenerateTokenReq
	GenerateTokenResp = pb.GenerateTokenResp
	RefreshTokenReq   = pb.RefreshTokenReq
	RefreshTokenResp  = pb.RefreshTokenResp
	RevokeTokenReq    = pb.RevokeTokenReq
	RevokeTokenResp   = pb.RevokeTokenResp
	ValidateTokenReq  = pb.ValidateTokenReq
	ValidateTokenResp = pb.ValidateTokenResp

	Auth interface {
		// 生成Token
		GenerateToken(ctx context.Context, in *GenerateTokenReq, opts ...grpc.CallOption) (*GenerateTokenResp, error)
		// 验证Token
		ValidateToken(ctx context.Context, in *ValidateTokenReq, opts ...grpc.CallOption) (*ValidateTokenResp, error)
		// 刷新Token
		RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error)
		// 注销Token
		RevokeToken(ctx context.Context, in *RevokeTokenReq, opts ...grpc.CallOption) (*RevokeTokenResp, error)
	}

	defaultAuth struct {
		cli zrpc.Client
	}
)

func NewAuth(cli zrpc.Client) Auth {
	return &defaultAuth{
		cli: cli,
	}
}

// 生成Token
func (m *defaultAuth) GenerateToken(ctx context.Context, in *GenerateTokenReq, opts ...grpc.CallOption) (*GenerateTokenResp, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.GenerateToken(ctx, in, opts...)
}

// 验证Token
func (m *defaultAuth) ValidateToken(ctx context.Context, in *ValidateTokenReq, opts ...grpc.CallOption) (*ValidateTokenResp, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.ValidateToken(ctx, in, opts...)
}

// 刷新Token
func (m *defaultAuth) RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.RefreshToken(ctx, in, opts...)
}

// 注销Token
func (m *defaultAuth) RevokeToken(ctx context.Context, in *RevokeTokenReq, opts ...grpc.CallOption) (*RevokeTokenResp, error) {
	client := pb.NewAuthClient(m.cli.Conn())
	return client.RevokeToken(ctx, in, opts...)
}
