// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"yiwen/go-wire/config"
	"yiwen/go-wire/handler"
	"yiwen/go-wire/repository"
	"yiwen/go-wire/service"
)

// Injectors from wire.go:

// InitializeApp 是一个 injector 函数
// Wire 会根据这个函数生成实际的依赖注入代码
// 函数体中的 wire.Build() 告诉 Wire 使用哪些 Provider
func InitializeApp() (*App, error) {
	configConfig := config.NewConfig()
	userRepository := repository.NewUserRepository()
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	app := NewApp(configConfig, userHandler)
	return app, nil
}

// wire.go:

// ProviderSet 是所有 Provider 的集合
// wire.NewSet 用于将多个 Provider 组合在一起
var ProviderSet = wire.NewSet(config.NewConfig, repository.NewUserRepository, service.NewUserService, handler.NewUserHandler)

// App 是应用程序的主结构体
type App struct {
	Config  *config.Config
	Engine  *gin.Engine
	Handler *handler.UserHandler
}

// NewApp 创建应用程序（这也是一个 Provider）
func NewApp(cfg *config.Config, h *handler.UserHandler) *App {
	engine := gin.Default()
	h.RegisterRoutes(engine)

	return &App{
		Config:  cfg,
		Engine:  engine,
		Handler: h,
	}
}
