// proto/hello.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.4
// source: proto/hello.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Creeter_SayHello_FullMethodName = "/hello.Creeter/SayHello"
)

// CreeterClient is the client API for Creeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CreeterClient interface {
	// 定义一个rpc方法 发送hellorequest 接受 helloresponse
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type creeterClient struct {
	cc grpc.ClientConnInterface
}

func NewCreeterClient(cc grpc.ClientConnInterface) CreeterClient {
	return &creeterClient{cc}
}

func (c *creeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, Creeter_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreeterServer is the server API for Creeter service.
// All implementations must embed UnimplementedCreeterServer
// for forward compatibility.
type CreeterServer interface {
	// 定义一个rpc方法 发送hellorequest 接受 helloresponse
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedCreeterServer()
}

// UnimplementedCreeterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCreeterServer struct{}

func (UnimplementedCreeterServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedCreeterServer) mustEmbedUnimplementedCreeterServer() {}
func (UnimplementedCreeterServer) testEmbeddedByValue()                 {}

// UnsafeCreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CreeterServer will
// result in compilation errors.
type UnsafeCreeterServer interface {
	mustEmbedUnimplementedCreeterServer()
}

func RegisterCreeterServer(s grpc.ServiceRegistrar, srv CreeterServer) {
	// If the following call panics, it indicates UnimplementedCreeterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Creeter_ServiceDesc, srv)
}

func _Creeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Creeter_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Creeter_ServiceDesc is the grpc.ServiceDesc for Creeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Creeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hello.Creeter",
	HandlerType: (*CreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Creeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/hello.proto",
}
