// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: auth.proto

package server

import (
	"context"

	"github.com/haoyiwen/go-examples/go-zero/auth-rpc/internal/logic"
	"github.com/haoyiwen/go-examples/go-zero/auth-rpc/internal/svc"
	"github.com/haoyiwen/go-examples/go-zero/auth-rpc/pb"
)

type AuthServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAuthServer
}

func NewAuthServer(svcCtx *svc.ServiceContext) *AuthServer {
	return &AuthServer{
		svcCtx: svcCtx,
	}
}

// 生成Token
func (s *AuthServer) GenerateToken(ctx context.Context, in *pb.GenerateTokenReq) (*pb.GenerateTokenResp, error) {
	l := logic.NewGenerateTokenLogic(ctx, s.svcCtx)
	return l.GenerateToken(in)
}

// 验证Token
func (s *AuthServer) ValidateToken(ctx context.Context, in *pb.ValidateTokenReq) (*pb.ValidateTokenResp, error) {
	l := logic.NewValidateTokenLogic(ctx, s.svcCtx)
	return l.ValidateToken(in)
}

// 刷新Token
func (s *AuthServer) RefreshToken(ctx context.Context, in *pb.RefreshTokenReq) (*pb.RefreshTokenResp, error) {
	l := logic.NewRefreshTokenLogic(ctx, s.svcCtx)
	return l.RefreshToken(in)
}

// 注销Token
func (s *AuthServer) RevokeToken(ctx context.Context, in *pb.RevokeTokenReq) (*pb.RevokeTokenResp, error) {
	l := logic.NewRevokeTokenLogic(ctx, s.svcCtx)
	return l.RevokeToken(in)
}
